server:
  port: 18081

dubbo:
  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://localhost
  cloud:
    subscribed-services: sca-provider
  consumer:
    check: false

spring:
  application:
    name: sca-customer
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: nacos
    password: nacos

  cloud:
    nacos:
      # Nacos 服务注册发现
      discovery:
        server-addr: 127.0.0.1:8848

mybatis:
  mapper-locations: classpath:mapper/*.xml
seata:
  tx-service-group: sca-customer-seata-tx-service-group


