"""empty message

Revision ID: f68e0ceef332
Revises: 
Create Date: 2019-05-20 15:53:05.318839

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f68e0ceef332'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('uniq_user_id', table_name='tbl_luban_user')
    op.drop_table('tbl_luban_user')
    op.drop_table('tbl_task_job')
    op.drop_table('bomcdata')
    op.drop_index('uniq_month_bizType', table_name='tbl_account_month_static')
    op.drop_table('tbl_account_month_static')
    op.drop_table('tbl_test_mitrics')
    op.drop_table('tbl_task_table_count')
    op.drop_table('tbl_task_email_group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_task_email_group',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='自增主键id'),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=False, comment='邮件组名称'),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=False, comment='邮件标题'),
    sa.Column('receive', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=False, comment='收件人，多个用英文逗号分隔'),
    sa.Column('cc', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=False, comment='抄送人，多个用英文逗号分隔'),
    sa.Column('status', mysql.TINYINT(display_width=2), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='状态，0不启动，1启动'),
    sa.Column('createTime', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), server_default=sa.text("''"), nullable=False, comment='创建时间'),
    sa.Column('actionTime', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), server_default=sa.text("''"), nullable=False, comment='更新时间'),
    sa.Column('createManager', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=False, comment='创建人'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tbl_task_table_count',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='自增主键id'),
    sa.Column('dbUrl', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=False, comment='数据库链接'),
    sa.Column('dbTableName', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=False, comment='数据表名称'),
    sa.Column('count', mysql.BIGINT(display_width=20), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='每天数据量'),
    sa.Column('createTime', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), server_default=sa.text("''"), nullable=False, comment='创建时间'),
    sa.Column('actionTime', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), server_default=sa.text("''"), nullable=False, comment='更新时间'),
    sa.Column('emailGroupId', mysql.BIGINT(display_width=20), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='邮件组id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tbl_test_mitrics',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='value'),
    sa.Column('metrics', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True, comment='metrics'),
    sa.Column('time_sec', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='time_sec'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tbl_account_month_static',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('monthStr', mysql.VARCHAR(length=10), server_default=sa.text("''"), nullable=False, comment='统计时间 Mar-19'),
    sa.Column('bizType', mysql.VARCHAR(length=5), server_default=sa.text("''"), nullable=False, comment='业务类型'),
    sa.Column('consumeAmt', mysql.DECIMAL(precision=16, scale=2), server_default=sa.text("'0.00'"), nullable=False, comment='消费金额'),
    sa.Column('consumeCount', mysql.BIGINT(display_width=12), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='消费笔数'),
    sa.Column('correctAmt', mysql.DECIMAL(precision=16, scale=2), server_default=sa.text("'0.00'"), nullable=False, comment='退回金额'),
    sa.Column('correctCount', mysql.BIGINT(display_width=12), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='退回笔数'),
    sa.Column('rechargeAmt', mysql.DECIMAL(precision=16, scale=2), server_default=sa.text("'0.00'"), nullable=False, comment='充值金额'),
    sa.Column('rechargeCount', mysql.BIGINT(display_width=12), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='充值笔数'),
    sa.Column('withdrawAmt', mysql.DECIMAL(precision=16, scale=2), server_default=sa.text("'0.00'"), nullable=False, comment='提现金额'),
    sa.Column('withdrawCount', mysql.BIGINT(display_width=12), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='提现笔数'),
    sa.Column('receiveAmt', mysql.DECIMAL(precision=16, scale=2), server_default=sa.text("'0.00'"), nullable=False, comment='领取金额'),
    sa.Column('receiveCount', mysql.BIGINT(display_width=12), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='领取笔数'),
    sa.Column('note', mysql.VARCHAR(length=100), server_default=sa.text("''"), nullable=False, comment='备注'),
    sa.Column('action', mysql.TINYINT(display_width=2), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='操作行为'),
    sa.Column('createStamp', mysql.TIMESTAMP(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False, comment='创建时间'),
    sa.Column('actionStamp', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('type', mysql.TINYINT(display_width=2), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='统计类型 0日统计 1月统计'),
    sa.Column('rechargeMoney', mysql.DECIMAL(precision=16, scale=2), server_default=sa.text("'0.00'"), nullable=False, comment='充值金额（元）'),
    sa.PrimaryKeyConstraint('id'),
    comment='权益账户月统计表',
    mysql_comment='权益账户月统计表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='COMPACT'
    )
    op.create_index('uniq_month_bizType', 'tbl_account_month_static', ['monthStr', 'bizType'], unique=True)
    op.create_table('bomcdata',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('id_key', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('date_time_date', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tbl_task_job',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='自增主键id'),
    sa.Column('dbUrl', mysql.VARCHAR(length=255), nullable=False, comment='数据库链接,最后附带库前缀'),
    sa.Column('dbSuffix', mysql.VARCHAR(length=255), nullable=False, comment='库后缀（只支持整数递增，咱不支持后缀带字母），示例：0000-0063（左闭右闭），反例：000a-000z，如果为""代表只扫描单库'),
    sa.Column('dbTableName', mysql.VARCHAR(length=255), nullable=False, comment='数据表名称前缀(如果为""代表扫描该库下所有数据表)'),
    sa.Column('dbTableSuffix', mysql.VARCHAR(length=255), nullable=False, comment='表后缀（只支持整数递增，咱不支持后缀带字母），示例：0000-0063（左闭右闭），反例：000a-000z，如果为""代表扫描该库下所有数据表'),
    sa.Column('dbUsername', mysql.VARCHAR(length=255), nullable=False, comment='数据库username'),
    sa.Column('dbPassword', mysql.VARCHAR(length=255), nullable=False, comment='数据库password'),
    sa.Column('status', mysql.TINYINT(display_width=2), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='状态，0停止，1启动'),
    sa.Column('createTime', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False, comment='创建时间'),
    sa.Column('actionTime', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False, comment='更新时间'),
    sa.Column('createManager', mysql.VARCHAR(length=255), nullable=False, comment='创建者'),
    sa.Column('emailGroupId', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='发送ID'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('tbl_luban_user',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False, comment='自增ID'),
    sa.Column('user_id', mysql.VARCHAR(length=50), server_default=sa.text("'none'"), nullable=False, comment='用户ID'),
    sa.Column('user_name', mysql.VARCHAR(length=50), server_default=sa.text("'none'"), nullable=False, comment='用户名称'),
    sa.Column('user_sex', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='用户性别(0-男,1-女)'),
    sa.Column('user_status', mysql.VARCHAR(length=10), server_default=sa.text("'none'"), nullable=False),
    sa.Column('user_status1', mysql.VARCHAR(length=10), server_default=sa.text("'none'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='广告路由表',
    mysql_comment='广告路由表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('uniq_user_id', 'tbl_luban_user', ['user_id'], unique=True)
    op.drop_table('article')
    # ### end Alembic commands ###
