spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: nacos
        url: jdbc:mysql://127.0.0.1:3306/test?connectTimeout=10000&socketTimeout=10000&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
        username: nacos
#        type: com.zaxxer.hikari.HikariDataSource
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
            filters: stat,wall
            initial-size: 5
            max-active: 20
            max-pool-prepared-statement-per-connection-size: 20
            max-wait: 10000
            min-evictable-idle-time-millis: 300000
            min-idle: 5
            pool-prepared-statements: true
            stat-view-servlet:
                allow: 127.0.0.1
                deny: 192.168.31.253
                login-password: 123
                login-username: root
                reset-enable: false
                url-pattern: /druid/*
            test-on-borrow: false
            test-on-return: false
            test-while-idle: true
            time-between-eviction-runs-millis: 60000
            validation-query: SELECT 1 FROM sys_user
            web-stat-filter:
                enabled: true
                exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
                url-pattern: /*

